name: Build Package

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - PKGBUILD
  pull_request:
    paths:
      - PKGBUILD

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel git
      - name: Create build user
        run: |
          useradd -m builder
          chown -R builder .
      - name: Build package
        run: su builder -c 'makepkg --syncdeps --noconfirm --skipinteg'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: openconnect-sso-plus
          path: '*.pkg.tar.zst'
